sitp_bot/urls.py
from django.conf.urls import url


from .views import TelegramCommandReceiveView, FacebookCommandReceiveView

urlpatterns = [
    url(
        r'fb-webhook/(?P<bot_keyword>.+)/$',
        FacebookCommandReceiveView.as_view(),
        name='fb_webhook',
    ),

    url(
        r'(?P<bot_token>.+)/$',
        TelegramCommandReceiveView.as_view(),
        name='telegram_webhook',
    ),
]

sitp_scraper/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib import admin

from .views import get_routes, get_route, RouteListView, RouteDetailView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^terms/$', TemplateView.as_view(template_name='terms.html'), name='terms'),
    url(r'^routes/$', RouteListView.as_view(), name='route_list'),
    url(r'^route/(?P<pk>\d+)/$', RouteDetailView.as_view(), name='route_detail'),
    url(r'^get_routes/$', get_routes, name='get_routes'),
    url(r'^get_route/(?P<pk>\d+)/$', get_route, name='get_route'),

    # Telegram bot
    url(r'^bot/', include('sitp_bot.urls', namespace='bot')),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

sitp_scrapper/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

sitp_scraper/models.py
from ast import literal_eval

from django.db import models
from django.contrib.gis.db import models as geo_models


class BusStation(models.Model):
    LOCATION_VERIFIED = 1
    LOCATION_PENDING = 2
    LOCATION_WRONG = 3

    name = models.CharField(max_length=150)
    code = models.CharField(max_length=30)
    link = models.URLField(default='')
    address = models.CharField(max_length=255)
    sublocality = models.CharField(max_length=150, default='', blank=True)
    location_status = models.PositiveSmallIntegerField(
        choices=(
            (LOCATION_VERIFIED, 'Correcto'),
            (LOCATION_PENDING, 'Por validar'),
            (LOCATION_WRONG, 'Incorrecto'),
        ),
        default=LOCATION_PENDING,
    )
    location = geo_models.PointField(null=True)
    longitude = models.FloatField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    source = models.CharField(max_length=30, default='', blank=True)

    related_stations = models.ManyToManyField('self', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    @staticmethod
    def autocomplete_search_fields():
        return ('code__iexact', 'name__icontains',)

    class Meta:
        ordering = ['address']


class RouteStations(models.Model):
    DIRECTION_1 = 1
    DIRECTION_2 = 2

    direction = models.PositiveSmallIntegerField(
        choices=((DIRECTION_1, 'Ida'), (DIRECTION_2, 'Vuelta')),
    )
    position = models.PositiveIntegerField()
    route = models.ForeignKey('sitp_scraper.Route',
                              related_name='route_stations')
    bus_station = models.ForeignKey(
        'sitp_scraper.BusStation', related_name='route_stations')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['direction', 'position']


class Route(models.Model):
    ROUTE_TYPE_URBAN = 8
    ROUTE_TYPE_COMPLEMENTARY = 9
    ROUTE_TYPE_SPECIAL = 10
    ROUTE_TYPES = (
        (6, 'Troncal Sistema TransMilenio'),
        (7, 'Alimentadora'),
        (8, 'Urbana'),
        (9, 'Complementaria'),
        (10, 'Especial'),
    )

    name = models.CharField(max_length=150)
    code = models.CharField(max_length=30)
    route_type = models.PositiveSmallIntegerField(choices=ROUTE_TYPES)
    map_link = models.URLField(default='')
    schedule = models.CharField(max_length=500)
    link = models.URLField(default='')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.code

    def get_schedule_display(self):
        try:
            schedule = literal_eval(self.schedule)
            return ', '.join(schedule)
        except:
            return ''

    class Meta:
        ordering = ['code']

sitp_scraper/views.py
from django.http import JsonResponse
from django.views.generic import ListView, DetailView

from .models import Route, BusStation, RouteStations


def get_routes(request):
    features = []
    for bus_station in BusStation.objects.prefetch_related('route_stations').all():
        if bus_station.location:
            routes = set(bus_station.route_stations.values_list(
                'route__code', flat=True,
            ))
            features.append({
                "type": "Feature",
                'properties': {
                    'title': '{}: {} ({})'.format(
                        bus_station.name,
                        bus_station.address,
                        ', '.join(routes)
                    ),
                    'marker-color': "#00608B",
                    'marker-size': 'small',
                    'marker-symbol': 'bus',
                },
                "geometry": {
                "type": "Point",
                "coordinates": [bus_station.location.x, bus_station.location.y]
                }
            })
    return JsonResponse({
      "type": "FeatureCollection",
      "features": features,
    })


def get_route(request, pk):
    features = []
    route = Route.objects.get(id=pk)
    for bs in route.route_stations.all():
        if bs.bus_station.location:
            features.append({
                "type": "Feature",
                "properties": {
                    "marker-color": "#00608B",
                    "marker-symbol": "bus",
                    "marker-size": "small",
                    "title": '{}: {}'.format(bs.bus_station.name, bs.bus_station.address)
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        bs.bus_station.location.x,
                        bs.bus_station.location.y,
                    ]
                }
            })
    bs_list = list(route.route_stations.filter(
        bus_station__location__isnull=False,
    ))
    for bs1, bs2 in zip(bs_list[:-1], bs_list[1:]):
        features.append({
            'type': 'Feature',
            'geometry': {
                'type': 'LineString',
                'coordinates': [
                    [bs1.bus_station.location.x, bs1.bus_station.location.y],
                    [bs2.bus_station.location.x, bs2.bus_station.location.y]
                ]
            },
            'properties': {
                "stroke": "#ff8888",
                "stroke-opacity": 1,
                "stroke-width": 4,
            }
        })
    return JsonResponse({
        "type": "FeatureCollection",
        "features": features,
    })


class RouteListView(ListView):
    template_name = 'route_list.html'
    model = Route


class RouteDetailView(DetailView):
    template_name = 'route_detail.html'
    model = Route

    def get_context_data(self, **kwargs):
        context = super(RouteDetailView, self).get_context_data(**kwargs)
        context['route_1'] = self.object.route_stations.filter(
            direction=RouteStations.DIRECTION_1,
        ).all()
        context['route_2'] = self.object.route_stations.filter(
            direction=RouteStations.DIRECTION_2,
        ).all()
        return context

sitp_scraper/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Cover Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.23.0/mapbox-gl.css' rel='stylesheet' />

    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
      body {
        padding-top: 60px;
      }

      #map {
        width:100%;
        height: 600px;
        padding: 40px 15px;
      }
    </style>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">SITP Scraper</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'route_list' %}">Routes</a></li>
            <li><a href="https://github.com/vero4karu/sitp_scraper">Source code</a></li>
            <li style="background-color: #0088CC;">
              <a style="color: #FFFFFF;" href="https://telegram.me/sitp_bot"><i class="fa fa-telegram"></i> Telegram bot</a>
            </li>
            <li style="background-color: #3b5998;">
              <a style="color: #FFFFFF;" href="https://www.facebook.com/SITPbot"><i class="fa fa-facebook"></i></a>
            </li>
            <li style="background-color: #00aced;">
              <a style="color: #FFFFFF;" href="https://twitter.com/sitp_bot"><i class="fa fa-twitter"></i></a>
            </li>
            <li><a href="{% url 'terms' %}">Terms</a></li>
            <li><a href="http://blog.vero4ka.info">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
      {% block content %}
      {% endblock %}

    </div><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.23.0/mapbox-gl.js'></script>

    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>

    {% block javascript %}
    {% endblock %}

  </body>
</html>

sitp_scraper/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <h2>SITP bus stations</h2>
  <div id="map"></div>
{% endblock %}

{% block javascript %}
  <script type="text/javascript">

  L.mapbox.accessToken = 'pk.eyJ1IjoidmVybzRrYSIsImEiOiJjYWNlMWY0Zjk0MGJhNWRmNDIzNmVjNjc0NDRhMjllOCJ9.fRmHavGBvl6wWemwMZBbfA';

  var map = L.mapbox.map('map')
      .setView([4.66336863727521, -74.07231699675322], 11)
      .addLayer(L.mapbox.tileLayer('mapbox.streets'));

  // Since featureLayer is an asynchronous method, we use the `.on('ready'`
  // call to only use its marker data once we know it is actually loaded.
  L.mapbox.featureLayer("{% url 'get_routes' %}").on('ready', function(e) {
      // The clusterGroup gets each marker in the group added to it
      // once loaded, and then is added to the map
      var clusterGroup = new L.MarkerClusterGroup();
      e.target.eachLayer(function(layer) {
        clusterGroup.addLayer(layer);
      });
      map.addLayer(clusterGroup);
  });

  </script>
{% endblock %}

sitp_scraper/templates/route_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>{{ object.code }}</h2>

  <div id="map"></div>

  <div class="row">
    <div class="col-md-6">
      <table class="table table-condensed">
       <tbody>
       {% for route_station in route_1 %}
        <tr>
          <td>{{ route_station.position }}</td>
          <td>{{ route_station.get_direction_display }}</td>
          <td>{{ route_station.bus_station.name }}</td>
          <td>{{ route_station.bus_station.address }}</td>
        </tr>
       {% endfor %}
       </tbody>
      </table>
    </div>
    <div class="col-md-6">
      <table class="table table-condensed">
       <tbody>
       {% for route_station in route_2 %}
        <tr>
          <td>{{ route_station.position }}</td>
          <td>{{ route_station.get_direction_display }}</td>
          <td>{{ route_station.bus_station.name }}</td>
          <td>{{ route_station.bus_station.address }}</td>
        </tr>
       {% endfor %}
       </tbody>
      </table>
    </div>
  </div>

{% endblock %}

{% block javascript %}
<script type="text/javascript">
  L.mapbox.accessToken = 'pk.eyJ1IjoidmVybzRrYSIsImEiOiJjYWNlMWY0Zjk0MGJhNWRmNDIzNmVjNjc0NDRhMjllOCJ9.fRmHavGBvl6wWemwMZBbfA';
  var map = L.mapbox.map('map', 'mapbox.streets')
    .setView([38, -102.0], 2);

  var featureLayer = L.mapbox.featureLayer()
    .loadURL("{% url 'get_route' object.id %}").addTo(map);

  featureLayer.on('ready', function() {
    map.fitBounds(featureLayer.getBounds());
  });
</script>
{% endblock %}

sitp_scraper/templates/route_list.html
{% extends 'base.html' %}

{% block content %}
  <table class="table table-condensed">
   <tbody>
   {% for object in object_list %}
    <tr>
      <td><a href="{% url 'route_detail' object.id %}">{{ object.code }}</a></td>
      <td>{{ object.name }}</td>
      <td>{{ object.get_route_type_display }}</td>
      <td>{{ object.updated_at }}</td>
    </tr>
   {% endfor %}
   </tbody>
  </table>
{% endblock %}

sitp_scraper/templates/terms.html
{% extends 'base.html' %}

{% block content %}
  <h2>Terms and Conditions</h2>

  <p>
    The following document outlines the terms of use of the SITP Bot.
    Before using SITP Bot you are required to read, understand, and agree
    to these terms.
  </p>

  <h4>Messenger Platforms</h4>

  <p>
    We develop SITP Bot to send you the information about SITP
    (Sistema Integrado de Transporte Público de Bogotá) routes and
    bus stations directly to your Facebook Messenger or Telegram chat.
    We will develop more features in the future.
    At times things can go wrong and the service may be interrupted.
    We may stop providing services at any time.
    You can stop using our bot at any time as well.
    You may need to visit this page regularly to see if these terms are changed.
    New terms may be published on this page without any additional notice.
  </p>

  <p>
    To use SITP Bot you should have a Facebook Messenger or Telegram account.
  </p>
  <p>
    SITP Bot is provided for free.
  </p>

  <h4>Data</h4>

  <p>
    Your data is your data. We will not collect this data and hence will not sell it
    to anyone without your permission.
  </p>

  <h2>Privacy Policy</h2>

  <p>
    We develop SITP Bot to send you the information about SITP
    (Sistema Integrado de Transporte Público de Bogotá) routes and
    bus stations directly to your Facebook Messenger or Telegram chat.

    We know that you care about how your data is used, and we take your privacy
    very seriously. By using SITP Bot, you are accepting the practices outlined in this policy.
  </p>

  <p>
    We don’t store any user specific data except the public information.
    This is the only information we keep.
  </p>

  <p>
    Our servers also collect log information used to identify bugs in our code.
    The information includes data sent to and from Facebook Messenger and Telegram.
    The old data is automatically deleted once log is full.
  </p>

  <p>
    Since we don’t know your email or phone number, we communicate with you only
    through your Facebook Messenger or Telegram account.
    But we don’t initiate discussion ourselves – we always wait for you to start.
    We do not sell your information to anyone.
    We don’t encrypt the data stored on our servers, but still it is safe.
  </p>

  <p>
    Privacy policy may change. Using SITP Bot is subject to Terms and Privacy policy.
  </p>
{% endblock %}